### ISSUE TITLE
일부 디자인 변경 및 QA 진행 (잔여 작업)

### ISSUE THREAD

**Issue by Chaemin-L** [hk-plantify/plantify-client#16]
## TODO
- [x] 내 카드 디자인 변경
- [x] ~~출석체크 기능 (삭제된 기능)~~
- [x] 페이지 접근 제한
- [ ] 인트로
